// Generated by gencpp from file twodto3d/twodto3d.msg
// DO NOT EDIT!


#ifndef TWODTO3D_MESSAGE_TWODTO3D_H
#define TWODTO3D_MESSAGE_TWODTO3D_H

#include <ros/service_traits.h>


#include <twodto3d/twodto3dRequest.h>
#include <twodto3d/twodto3dResponse.h>


namespace twodto3d
{

struct twodto3d
{

typedef twodto3dRequest Request;
typedef twodto3dResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct twodto3d
} // namespace twodto3d


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::twodto3d::twodto3d > {
  static const char* value()
  {
    return "0a72e6459b11515d7f19e6e41260f1a9";
  }

  static const char* value(const ::twodto3d::twodto3d&) { return value(); }
};

template<>
struct DataType< ::twodto3d::twodto3d > {
  static const char* value()
  {
    return "twodto3d/twodto3d";
  }

  static const char* value(const ::twodto3d::twodto3d&) { return value(); }
};


// service_traits::MD5Sum< ::twodto3d::twodto3dRequest> should match 
// service_traits::MD5Sum< ::twodto3d::twodto3d > 
template<>
struct MD5Sum< ::twodto3d::twodto3dRequest>
{
  static const char* value()
  {
    return MD5Sum< ::twodto3d::twodto3d >::value();
  }
  static const char* value(const ::twodto3d::twodto3dRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::twodto3d::twodto3dRequest> should match 
// service_traits::DataType< ::twodto3d::twodto3d > 
template<>
struct DataType< ::twodto3d::twodto3dRequest>
{
  static const char* value()
  {
    return DataType< ::twodto3d::twodto3d >::value();
  }
  static const char* value(const ::twodto3d::twodto3dRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::twodto3d::twodto3dResponse> should match 
// service_traits::MD5Sum< ::twodto3d::twodto3d > 
template<>
struct MD5Sum< ::twodto3d::twodto3dResponse>
{
  static const char* value()
  {
    return MD5Sum< ::twodto3d::twodto3d >::value();
  }
  static const char* value(const ::twodto3d::twodto3dResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::twodto3d::twodto3dResponse> should match 
// service_traits::DataType< ::twodto3d::twodto3d > 
template<>
struct DataType< ::twodto3d::twodto3dResponse>
{
  static const char* value()
  {
    return DataType< ::twodto3d::twodto3d >::value();
  }
  static const char* value(const ::twodto3d::twodto3dResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TWODTO3D_MESSAGE_TWODTO3D_H
