// Generated by gencpp from file calibration_glasgow/HandEyeCalibrationRequest.msg
// DO NOT EDIT!


#ifndef CALIBRATION_GLASGOW_MESSAGE_HANDEYECALIBRATIONREQUEST_H
#define CALIBRATION_GLASGOW_MESSAGE_HANDEYECALIBRATIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace calibration_glasgow
{
template <class ContainerAllocator>
struct HandEyeCalibrationRequest_
{
  typedef HandEyeCalibrationRequest_<ContainerAllocator> Type;

  HandEyeCalibrationRequest_()
    : doIt(false)  {
    }
  HandEyeCalibrationRequest_(const ContainerAllocator& _alloc)
    : doIt(false)  {
  (void)_alloc;
    }



   typedef uint8_t _doIt_type;
  _doIt_type doIt;





  typedef boost::shared_ptr< ::calibration_glasgow::HandEyeCalibrationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::calibration_glasgow::HandEyeCalibrationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct HandEyeCalibrationRequest_

typedef ::calibration_glasgow::HandEyeCalibrationRequest_<std::allocator<void> > HandEyeCalibrationRequest;

typedef boost::shared_ptr< ::calibration_glasgow::HandEyeCalibrationRequest > HandEyeCalibrationRequestPtr;
typedef boost::shared_ptr< ::calibration_glasgow::HandEyeCalibrationRequest const> HandEyeCalibrationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::calibration_glasgow::HandEyeCalibrationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::calibration_glasgow::HandEyeCalibrationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace calibration_glasgow

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::calibration_glasgow::HandEyeCalibrationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::calibration_glasgow::HandEyeCalibrationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::calibration_glasgow::HandEyeCalibrationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::calibration_glasgow::HandEyeCalibrationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::calibration_glasgow::HandEyeCalibrationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::calibration_glasgow::HandEyeCalibrationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::calibration_glasgow::HandEyeCalibrationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3e7f2a3e38a161dfeb4d7798675f26e6";
  }

  static const char* value(const ::calibration_glasgow::HandEyeCalibrationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3e7f2a3e38a161dfULL;
  static const uint64_t static_value2 = 0xeb4d7798675f26e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::calibration_glasgow::HandEyeCalibrationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "calibration_glasgow/HandEyeCalibrationRequest";
  }

  static const char* value(const ::calibration_glasgow::HandEyeCalibrationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::calibration_glasgow::HandEyeCalibrationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool doIt\n\
";
  }

  static const char* value(const ::calibration_glasgow::HandEyeCalibrationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::calibration_glasgow::HandEyeCalibrationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.doIt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HandEyeCalibrationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::calibration_glasgow::HandEyeCalibrationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::calibration_glasgow::HandEyeCalibrationRequest_<ContainerAllocator>& v)
  {
    s << indent << "doIt: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.doIt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CALIBRATION_GLASGOW_MESSAGE_HANDEYECALIBRATIONREQUEST_H
